/*function saudacao(nome) {
    return `Bom dia ${nome}`
}

const varialvel = saudacao('Ricardo')
console.log(varialvel)


function soma(x, y){
    const resultado = x + y // os conteudos que estao na funcão somente podem ser acessados pela funcção. 
    return resultado //tudo abaixo de return não é executado, então não mandar nada abaixo dele.
}

console.log(soma(2, 2))
console.log(soma(32, 56))
console.log(soma(7, -1))
console.log(soma(77, 22.4))





const raiz = function(n){
    return n ** 0.5
};//Nas funcções anonimas é preciso colocar ;

console.log(raiz(9));

*/



function nomeCompleto(nome, sobrenome1, sobrenome2){
    const nome = prompt('Digite seu nome')
    const sobrenome1 = prompt('Digite seu sobrenome')
    const sobrenome2 = prompt('Digite seu ultimo sobrenome')

    const resultado = document.getElementById('texto')
    
}








